---
sudo: false
language: ruby

cache:
  bundler: true

env:
  global:
    - NOKOGIRI_USE_SYSTEM_LIBRARIES=1
    - CI=1

rvm:
  - 2.3.1
  - 2.4.2

jdk:
  - oraclejdk11

services:
  - redis-server

before_install:
  - curl -sLO https://projects.iq.harvard.edu/files/fits/files/fits-0.8.6_1.zip
  - unzip fits-0.8.6_1.zip
  - chmod +x fits-0.8.6/fits.sh
  - export PATH="$(pwd)/fits-0.8.6:$PATH"

before_script:
  - cp config/secrets.yml.template config/secrets.yml

notifications:
  email: false
