defaults: &defaults
  adapter: solr

development:
  <<: *defaults
  url: <%= ENV['DEV_SOLR_URL'] || 'http://localhost:8985/solr/development' %>

test:
  <<: *defaults
  url: <%= ENV['TEST_SOLR_URL'] || 'http://localhost:8985/solr/test' %>

production:
  <<: *defaults
  url: http://localhost:<%= ENV['TEST_JETTY_PORT'] || 8080 %>/hydra
