defaults: &defaults
  adapter: solr
  url: http://localhost:<%= ENV['TEST_JETTY_PORT'] || 8080 %>/hydra

development:
  <<: *defaults

test:
  <<: *defaults
  url: http://localhost:<%= ENV['TEST_JETTY_PORT'] || 8983 %>/hydra

production:
  <<: *defaults
