defaults: &defaults
  password: <%= Rails.application.secrets.fedora_pass %>
  url: http://localhost:<%= ENV['TEST_JETTY_PORT'] || 8080 %>/fedora/rest
  user: fedoraAdmin

development:
  <<: *defaults
  url: <%= ENV['DEV_FEDORA_URL'] || 'http://localhost:8984/rest' %>
  base_path: <%= ENV['DEV_FEDORA_BASE'] || "/devel" %>

test:
  <<: *defaults
  url: <%= ENV['TEST_FEDORA_URL'] || 'http://localhost:8986/rest' %>
  base_path: /test

production:
  <<: *defaults
  base_path: /prod
