---
- ark: 'ark:/48907/f37d2sf6'
  collection_id: 'f3d50k99'
  collection_title: 'Verne Todd collection'
  image_path: 'homepage/Performing Arts Vogue R 710-2000x1311.jpg'
  title: 'The Bells of St. Mary’s'

- ark: 'ark:/48907/f3qc01qx'
  collection_id: 'f3k35rv9'
  collection_title: 'Santa Barbara picture postcards collection'
  image_path: 'homepage/cusbspcmss36-110002-2000x1311.jpg'
  title: 'Red Rock Cut, Mountain Drive'

- ark: 'ark:/48907/f3qz29qv'
  collection_id: 'f3251hxt'
  collection_title: 'Community Development and Conservation collection'
  image_path: 'homepage/sbhcmss1-g00165-2000x1311.jpg'
  title: 'Early days in Santa Barbara, California'

- ark: 'ark:/48907/f36w99vz'
  collection_id: 'f3251hxt'
  collection_title: 'Community Development and Conservation collection'
  image_path: 'homepage/sbhcmss1-g00378-2000x1311.jpg'
  title: 'Greetings from beautiful Santa Barbara'

- ark: 'ark:/48907/f3bv7gdb'
  collection_id: 'f3251hxt'
  collection_title: 'Community Development and Conservation collection'
  image_path: 'homepage/sbhcmss1-g00524-2000x1311.jpg'
  title: 'Looking down State Street from the air. A general view of the business area of Santa Barbara, California'

- ark: 'ark:/48907/f3fb52nh'
  collection_id: 'f3f76c59'
  collection_title: 'Ronald H. McPeak underwater and coastal California photographs'
  image_path: 'homepage/mss292-g00774-2000x1311.jpg'
  title: 'Asteroidea'

- ark: 'ark:/48907/f31g0m45'
  collection_id: 'f3f76c59'
  collection_title: 'Ronald H. McPeak underwater and coastal California photographs'
  image_path: 'homepage/mss292-g01386-2000x1311.jpg'
  title: 'Giant kelp forest'

- ark: 'ark:/48907/f3ws8st3'
  collection_id: 'f3kd1xg1'
  collection_title: 'Arthur London / Gold Coast [Ghana] photograph collection'
  image_path: 'homepage/bernathmss315-03-loose3t-2000x1311.jpg'
  title: 'German submarine U. 118 on beach in Hastings'

- ark: 'ark:/48907/f33778fx'
  collection_id: 'f3s75g1g'
  collection_title: 'Bernard Herrmann papers'
  image_path: 'homepage/pamss03-081-2000x1311.jpg'
  title: 'Bernard Herrmann Christmas Carol sessions, December 1954'

- ark: 'ark:/48907/f3h9951g'
  collection_id: 'f3hd7vdz'
  collection_title: 'University Archives photographs collection'
  image_path: 'homepage/uarch112-g00553-2000x1311.jpg'
  title: 'University of California Santa Barbara College'

- ark: 'ark:/48907/f3dj5dfq'
  collection_id: 'f3th8mmz'
  collection_title: 'Cylinder Audio Archive'
  image_path: 'homepage/cylinders-2000x1311.jpg'
  title: 'Wax cylinders, including “La Traviata air”'
