collection:
    persist: false
    dir: solr/config/
    name: development
instance_dir: tmp/solr-development
managed: true
port: 8983
solr_xml: solr/config/solrconfig.xml
verbose: true
version: 6.3.0
