---
ark_shoulder: <%= Rails.application.secrets.ezid_default_shoulder %>
host: <%= Rails.application.secrets.sru_host %>
default_params:
  # https://developers.exlibrisgroup.com/alma/integrations/SRU
  - "version=1.2"
  - "operation=searchRetrieve"
  - "alma.mms_tagSuppressed=false"
binary_query: "(marc.956.f=%<binary>s)"
ark_query: "(alma.standard_number=%<ark_shoulder>s/%<ark>s)"
etd_query: "(marc.947.a=pqd)"
cylinder_query: "(alma.all_for_ui=*OBJID/Cylinder%<number>s)"
