---
ark_shoulder: <%= Rails.application.secrets.ezid_default_shoulder %>
# How many records can be fetched at once
batch_size: 50
host: <%= Rails.application.secrets.sru_host %>
default_params:
  # https://developers.exlibrisgroup.com/alma/integrations/SRU
  - "version=1.2"
  - "operation=searchRetrieve"
  - "alma.mms_tagSuppressed=false"
ark_query: "(alma.standard_number=%<ark_shoulder>s/%<ark>s)"
binary_query: "(alma.local_field_956=%<binary>s)"
cylinder_query: "(alma.all_for_ui=*OBJID/Cylinder%<number>s)"
etd_query: "(alma.local_field_947=pqd)"
